const TechData =[
    {
        heading:'Systems to Live and Breathe',
        details:'As humans travel farther from Earth for longer missions, the systems that keep them alive must be highly reliable while taking up minimal mass and volume. Orion will be equipped with advanced environmental control and life support systems designed for the demands of a deep space mission. A high-tech system already being tested aboard the space station will remove carbon dioxide (CO2) and humidity from inside Orion. Removal of CO2 and humidity is important to ensure air remains safe for the crew breathing. And water condensation on the vehicle hardware is controlled to prevent water intrusion into sensitive equipment or corrosion on the primary pressure structure.The system also saves volume inside the spacecraft. Without such technology, Orion would have to carry many chemical canisters that would otherwise take up the space of 127 basketballs (or 32 cubic feet) inside the spacecraft—about 10 percent of crew livable area. Orion will also have a new compact toilet, smaller than the one on the space station. Long duration missions far from Earth drive engineers to design compact systems not only to maximize available space for crew comfort, but also to accommodate the volume needed to carry consumables like enough food and water for the entirety of a mission lasting days or weeks.Highly reliable systems are critically important when distant crew will not have the benefit of frequent resupply shipments to bring spare parts from Earth, like those to the space station. Even small systems have to function reliably to support life in space, from a working toilet to an automated fire suppression system or exercise equipment that helps astronauts stay in shape to counteract the zero-gravity environment in space that can cause muscle and bone atrophy. Distance from home also demands that Orion have spacesuits capable of keeping astronaut alive for six days in the event of cabin depressurization to support a long trip home.'
    },
    {
        heading:'Proper Propulsion',
        details:'The farther into space a vehicle ventures, the more capable its propulsion systems need to be to maintain its course on the journey with precision and ensure its crew can get home.Orion has a highly capable service module that serves as the powerhouse for the spacecraft, providing propulsion capabilities that enable Orion to go around the Moon and back on its exploration missions. The service module has 33 engines of various sizes. The main engine will provide major in-space maneuvering capabilities throughout the mission, including inserting Orion into lunar orbit and also firing powerfully enough to get out of the Moon’s orbit to return to Earth. The other 32 engines are used to steer and control Orion on orbit.In part due to its propulsion capabilities, including tanks that can hold nearly 2,000 gallons of propellant and a back up for the main engine in the event of a failure, Orion’s service module is equipped to handle the rigors of travel for missions that are both far and long, and has the ability to bring the crew home in a variety of emergency situations.'
    },
    {
        heading:'The Ability to Hold Off the Heat',
        details:'Going to the Moon is no easy task, and it’s only half the journey. The farther a spacecraft travels in space, the more heat it will generate as it returns to Earth. Getting back safely requires technologies that can help a spacecraft endure speeds 30 times the speed of sound and heat twice as hot as molten lava or half as hot as the sun.When Orion returns from the Moon, it will be traveling nearly 25,000 mph, a speed that could cover the distance from Los Angeles to New York City in six minutes. Its advanced heat shield, made with a material called AVCOAT, is designed to wear away as it heats up. Orion’s heat shield is the largest of its kind ever built and will help the spacecraft withstand temperatures around 5,000 degrees Fahrenheit during reentry though Earth’s atmosphere.Before reentry, Orion also will endure a 700-degree temperature range from about minus 150 to 550 degrees Fahrenheit. Orion’s highly capable thermal protection system, paired with thermal controls, will protect Orion during periods of direct sunlight and pitch black darkness while its crews will comfortably enjoy a safe and stable interior temperature of about 77 degrees Fahrenheit.'
    },
    {
        heading:'Radiation Protection',
        details:'As a spacecraft travels on missions beyond the protection of Earth’s magnetic field, it will be exposed to a harsher radiation environment than in low-Earth orbit with greater amounts of radiation from charged particles and solar storms that can cause disruptions to critical computers, avionics and other equipment. Humans exposed to large amounts of radiation can experience both acute and chronic health problems ranging from near-term radiation sickness to the potential of developing cancer in the long-term.Orion was designed from the start with built in system-level features to ensure reliability of essential elements of the spacecraft during potential radiation events. For example, Orion is equipped with four identical computers that each are self-checking, plus an entirely different backup computer, to ensure Orion can still send commands in the event of a disruption. Engineers have tested parts and systems to a high standard to ensure that all critical systems remain operable even under extreme circumstances.Orion also has a makeshift storm shelter below the main deck of the crew module. In the event of a solar radiation event, NASA has developed plans for crew on board to create a temporary shelter inside using materials on board. A variety of radiation sensors will also be on the spacecraft to help scientists better understand the radiation environment far away from Earth. One investigation called AstroRad, will fly on Artemis I and test an experimental vest that has the potential to help shield vital organs and decrease exposure from solar particle events.'
    },
    {
        heading:'Constant Communication and Navigation',
        details:'Spacecraft venturing far from home go beyond the Global Positioning System (GPS) in space and above communication satellites in Earth orbit. To talk with mission control in Houston, Orion will use all three of NASA’s space communications networks. As it rises from the launch pad and into cislunar space, Orion will switch from the Near Earth Network to the Space Network, made possible by the Tracking and Data Relay Satellites, and finally to the Deep Space Network that provides communications for some of NASA’s most distant spacecraft. Orion is also equipped with backup communication and navigation systems to help the spacecraft stay in contact with the ground and orient itself if it’s primary systems fail. The backup navigation system, a relatively new technology called optical navigation, uses a camera to take pictures of the Earth, Moon and stars and autonomously triangulate Orion’s position from the photos. Its backup emergency communications system doesn’t use the primary system or antennae for high-rate data transfer.'
    },
]
export default TechData ;